# Generated by Django 6.0.1 on 2026-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('remainingAmount', models.IntegerField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
