# Generated by Django 6.0.1 on 2026-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
