# Generated by Django 6.0.1 on 2026-01-29 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='remainingAmount',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
