# Generated by Django 6.0.1 on 2026-01-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
